### PR TITLE
Po filename customization + multiple po sources

### PR DESCRIPTION
**Pull request by Sshnyari**
see #305

### CODE REVIEW

**Comment by turquoiseowl** [comment]
Are you able to inclkude a README section to help me and others understand your new feature. Thanks.

**Comment by turquoiseowl** [comment]
Nice work, thanks.

**Comment by turquoiseowl** [comment]
Just noticed a possible bug introduced by this code.

Before this change, repeated running of PostBuild on a static source file was resulting in the following message in a PO file:

```
#: Controllers\AccountController.cs:336
msgid "Account creation failed"
msgstr ""
```

Now I'm getting the message entry as follows:

```
# Controllers\AccountController.cs:336
#: Controllers\AccountController.cs:336
#, Controllers\AccountController.cs:336
msgid "Account creation failed"
msgstr ""
```

which I don't think is correct.

Are you able to look into this please? Thanks.

**Comment by turquoiseowl** [comment]
@Sshnyari  To be clear, the first time PostBuild is run, all is correct; it's the second and subsequent times that cause the suspect output.

**Comment by Sshnyari** [comment]
Weird
I also had this issue with a custom post build project, but when I tested it with the solution's post build it seemed to disapear.
I didn't look too much into it.

I have a question about this bit of code (POTranslationRepository.cs:477) :
`                                        (k, v) =>
                                        {
                                            v.References = v.References.Append(item.References);
                                            var referencesAsComments =
                                                item.References.Select(r => r.ToComment()).ToList();
                                            v.ExtractedComments = v.ExtractedComments.Append(referencesAsComments);
                                            v.TranslatorComments = v.TranslatorComments.Append(referencesAsComments);
                                            v.Flags = v.Flags.Append(referencesAsComments);
                                            return v;
                                        });`

Why are references appended to Flags and translator comments ?
Is this a PO requirement ?

**Comment by turquoiseowl** [comment]
I don't know off-hand.

**Comment by Sshnyari** [comment]
Ok, I'll try to fix it without touching that then

**Comment by Sshnyari** [comment]
it should be OK now in #320

**Pull request merged**
