### PR TITLE
#173 add new param on constructor web config setting service

### PR DESCRIPTION
**Pull request by jonnybee**

### CODE REVIEW

**Comment by turquoiseowl** [comment]
We've got issues again here with full-file modifications. Any idea what's going on?

**Comment by jonnybee** [comment]
My only guess is a change of line endings – unix vs windows style. 

 

I noticed the same immediately after Clone of the repository. 

 

I added the default .gitattributes in Visual Studio (in previous checkin) and this now specifies: 

###############################################################################

# Set default behavior to automatically normalize line endings.

###############################################################################

* text=auto

 

Normally – this implies that 

-          Repo has Unix style line endings (LF)

-          GIT locally will convert to Windows style in working folder (CR+LF) and back to LF on checkin

(assuming GIT identifies the extension as text)

 

/Jonny

**Comment by turquoiseowl** [comment]
I'm thinking I might need to do something savage like what's outlined here:

 

https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings

**Comment by turquoiseowl** [comment]
In the hope of sorting out this "Wall of Pink" issue, I've done the following:

1. Set my local git setup so that core.autocrlf = true: ```git config --global core.autocrlf true```

2. Followed the instructions for refreshing the repo after this change as outlined here: https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings

The steps at 2. did not cause any files to be changed, either in the repo or those checked out.

So I remain stumped as to why this PR has a wall of pink.

**Comment by turquoiseowl** [comment]
Jonny, I've tried the line-ending normalization again and it worked. I'd be grateful if you would re-re-submit this PR! Thanks.

**Comment by turquoiseowl** [comment]
Full details on what I did here:

https://github.com/turquoiseowl/i18n#line-endings

**Comment by jonnybee** [comment]
Will do. Have a look at this sample project too: https://github.com/jonnybee/fluent_i18n_demo

**Comment by jonnybee** [comment]
I make "pull" to my repo from v2.0 od a further "pull" to my working branch. The changes should already be reflected in the existing PR.

**Comment by turquoiseowl** [comment]
Excellent, thanks.

**Pull request merged**
