### PR TITLE
wildcards for blacklists and disabling generated references

### PR DESCRIPTION
**Pull request by Sshnyari**
see #303 and #304

### CODE REVIEW

**Comment by turquoiseowl** [comment]
I take it this PR has two features? Are you able to submit individually?

Are you be able to include a README section on this? It will help others to use this feature and also me to work out what I'm looking at.

There is a method called ```TransformToken``` with nothing else to help me and others work out what it does.

(By Search Character do you mean Wildcard Character?)

Tests are appreciated, thanks; but more comments in them would be appreciated.

**Comment by Sshnyari** [comment]
I can split it into two different PR, but one is dependant on the other
They both use the same newelly created files (unit test files)

**Comment by Sshnyari** [comment]
How do you suggest we do this ?
Which feature should come first ?

**Comment by turquoiseowl** [comment]
The DisableReferences code looks good as is if you are able to resubmit that along with the README section.

WRT the wildcard code, please see notes above, thanks.

**Pull request closed without merging**
