### PR TITLE
V2 0

### PR DESCRIPTION
**Pull request by gitsno**
Added strong name signing to the i18n project using the same key as the i18n.Domain project, this is needed in order to use the library from projects that are strong named.

Renamed PostbackParser to AsyncPostbackParser as it is not used for standard postbacks

Made the list of types that are localized for async postbacks configurable with a new AsyncPostbackTypesToTranslate field in LocalizedApplication
Added pageTitle to the list of default types that are localized for async postbacks
Updated the README with the new AsyncPostbackTypesToTranslate field

### CODE REVIEW

**Comment by turquoiseowl** [comment]
We've a wall of pink here:

https://github.com/gitsno/i18n/commit/6ddca206efb852c14c9fac681501716916be7f75

Is that intentional?

I thought I had solved that following modifications done relating to: https://github.com/turquoiseowl/i18n/pull/180

Thanks.

**Comment by gitsno** [comment]
Yes, it is a line endings issue, and I didn't really want to do it, but I had to commit those changes in order to get the rest of my changes to commit.

**Comment by turquoiseowl** [comment]
I'm reluctant to merge into the repo files with de-normalized line endings.

The repo is now standardized on single LF endings: https://github.com/turquoiseowl/i18n#line-endings for more details.

Can you confirm what the line-endings are on those files?

**Comment by gitsno** [comment]
I tried deleting my fork completely, but whether I clone a new fork or I clone the main repo, git wants to commit those 14 files and all are line ending changes only. I do have core.autocrlf set to true and when I look at the files in a hex viewer, they all show CRLF line endings as they should, so I don't know what else to suggest. Can you try a fresh clone and see if git shows those files as having changed?

**Comment by turquoiseowl** [comment]
Yes, same issue here when I clone.

I've committed those 14 changed files in the cloned repo and pushed the changes up to origin. Hopefully that's fixed at your end now...

**Comment by gitsno** [comment]
I recreated my fork and it's fine now. I have committed again without the line endings commit - new pull request in #191, so you can kill this one.

**Comment by turquoiseowl** [comment]
Nice one, cheers.

**Pull request closed without merging**
