### PR TITLE
Quick fix for allowing unicode encoded strings to be translated #355

### PR DESCRIPTION
**Pull request by zingix**
The following modification allows also JSON encoded responses to be translated correctly.

### CODE REVIEW

**Comment by turquoiseowl** [comment]
Looks good. How about a couple of optimizations?

Firstly, to avoid double lookup when not necessary:

```
if (text == null && msgkey.Contains("\\u")) { ... }
```

Secondly, how about creating the RegEx as a static member object of that TextLocalizer class, just in case it is re-created each time? Probably doesn't and in fact get's cached, but it would be in keeping with all other regex usage in the lib.

Cheers.

**Comment by turquoiseowl** [comment]
Suppose the Regex object could then also be used for test for a match, in preference to using ```Contains```

**Comment by zingix** [comment]
Correct, that is a good point. Added a compiled regex and the required test.

**Comment by turquoiseowl** [comment]
Nice PR, thanks for contributing.

**Pull request merged**
